export const produtos = [
  {
    id: 1,
    image: "https://via.placeholder.com/250",
    title: "Produto número 1",
    text: "Texto com a descrição referente ao produto número 1",
    price: "R$ 25,00",
  },
  {
    id: 2,
    image: "https://via.placeholder.com/250",
    title: "Produto número 2",
    text: "Texto com a descrição referente ao produto número 2",
    price: "R$ 35,00",
  },
  {
    id: 3,
    image: "https://via.placeholder.com/250",
    title: "Produto número 3",
    text: "Texto com a descrição referente ao produto número 3",
    price: "R$ 45,00",
  },
  {
    id: 4,
    image: "https://via.placeholder.com/250",
    title: "Produto número 4",
    text: "Texto com a descrição referente ao produto número 4",
    price: "R$ 55,00",
  },
  {
    id: 5,
    image: "https://via.placeholder.com/250",
    title: "Produto número 5",
    text: "Texto com a descrição referente ao produto número 5",
    price: "R$ 65,00",
  },
  {
    id: 6,
    image: "https://via.placeholder.com/250",
    title: "Produto número 6",
    text: "Texto com a descrição referente ao produto número 6",
    price: "R$ 75,00",
  },
  {
    id: 7,
    image: "https://via.placeholder.com/250",
    title: "Produto número 7",
    text: "Texto com a descrição referente ao produto número 7",
    price: "R$ 85,00",
  },
  {
    id: 8,
    image: "https://via.placeholder.com/250",
    title: "Produto número 8",
    text: "Texto com a descrição referente ao produto número 8",
    price: "R$ 95,00",
  },
  {
    id: 9,
    image: "https://via.placeholder.com/250",
    title: "Produto número 9",
    text: "Texto com a descrição referente ao produto número 9",
    price: "R$ 105,00",
  },
  {
    id: 10,
    image: "https://via.placeholder.com/250",
    title: "Produto número 10",
    text: "Texto com a descrição referente ao produto número 10",
    price: "R$ 115,00",
  },
  {
    id: 11,
    image: "https://via.placeholder.com/250",
    title: "Produto número 11",
    text: "Texto com a descrição referente ao produto número 11",
    price: "R$ 125,00",
  },
  {
    id: 12,
    image: "https://via.placeholder.com/250",
    title: "Produto número 12",
    text: "Texto com a descrição referente ao produto número 12",
    price: "R$ 135,00",
  },
];
